### ISSUE TITLE
[list]  Company  - sb components

### ISSUE THREAD

**Issue by ariperez** [graydigital/storybook#57]

**Comment by BrandonClapp** [comment]
@ariperez Is this the section for recreating this? 
![image](https://user-images.githubusercontent.com/2096746/141519979-3060f8dd-9e3e-4c77-8538-494dd344ae47.png)

If so, this is what I'll tackle next.

**Comment by ariperez** [comment]
Yea, I need to catch up on breaking this down into tickets a bit better.  

This issue was meant to capture the `/copmpany` page.

Above image should work better with https://github.com/graydigital/storybook/issues/71
