### ISSUE TITLE
[create] SideBySide / Side By Side Left -- `/landing`

### ISSUE THREAD

**Issue by ariperez** [graydigital/storybook#71]
location: https://www.gray.digital

storybook name: sections/<<creators-choice>>

![image](https://user-images.githubusercontent.com/2553469/141520379-4ce8c640-cf1d-4c0f-a513-87efd8532cc2.png)

**Comment by BrandonClapp** [comment]
A lot of the sections on the website are this same "image on one side + paragraph blurb on the other". I'm going to make something more reusable so that we can use it to knock out the other similar sections quicker.
