### ISSUE TITLE
[bug] some config is trying to load an outdated Chakra UI lib

### ISSUE THREAD

**Issue by ariperez** [graydigital/storybook#98]
![image](https://user-images.githubusercontent.com/2553469/142441278-61eaccc1-90db-419a-881f-87e5d8e0a9ca.png)

**Comment by BrandonClapp** [comment]
I'll take a look

**Comment by ariperez** [comment]
I added the refs section her which is loading correctly.

![image](https://user-images.githubusercontent.com/2553469/142441714-e82fec25-b1b9-4dc5-9776-97d58f0a4b89.png)

**Comment by BrandonClapp** [comment]
I don't think this is an issue anymore 
![image](https://user-images.githubusercontent.com/2096746/142748859-7c04b796-0f9d-4839-bb2a-e19e7038fa0a.png)
